# Generated by Django 5.2 on 2025-05-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sectorsubdivisiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
