# Generated by Django 5.2 on 2025-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tracker', '0002_alter_employee_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorsubdivisiontype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='woreda',
            unique_together={('name', 'subcity')},
        ),
    ]
