# Generated by Django 5.2.3 on 2025-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tracker', '0003_alter_sectorsubdivisiontype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
