# Generated by Django 5.2 on 2025-05-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sector Office', 'Sector Office'), ('Subcity', 'Subcity'), ('College', 'College'), ('Hospital', 'Hospital')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Expert', 'Expert')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SectorSubdivisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubcitySubdivisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Woreda', 'Woreda')], default='Woreda', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_employees_no', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.division')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.organizationalunit')),
                ('sector_subdiv_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.sectorsubdivisiontype')),
                ('subcity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.subcity')),
                ('subcity_subdiv_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.subcitysubdivisiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=50)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.employeerole')),
                ('organizationalunit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.organizationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.subcity')),
            ],
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='woreda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_tracker.woreda'),
        ),
    ]
